FROM pytorch/pytorch:2.5.1-cuda12.4-cudnn9-devel

WORKDIR /app

COPY src ./src/
COPY tests ./tests/
COPY requirements.txt .
COPY pytest.ini .
COPY config.json .

ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
ENV PATH=/usr/local/cuda/bin:$PATH
ENV HF_HOME=/root/.cache/huggingface
ENV HF_HUB_HTTP_TIMEOUT=1000

RUN pip3 install --no-cache-dir -r requirements.txt

CMD bash -c "pytest ./tests/integration --maxfail=3 && sleep 10 && pytest ./tests/unit --maxfail=3"
