global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "Real_Time_Monitoring"
    static_configs:
      - targets: ["host.docker.internal:8000"]

  - job_name: "Benchmarking_Monitoring"
    static_configs:
      - targets: ["host.docker.internal:9200"]
